### ISSUE TITLE
Markers should indicate users info

### ISSUE THREAD

**Issue by Israel-Laguan** [r0binxp/tableworks#2]
# Description

When I see the map I can not select markers or know what they represent.

https://user-images.githubusercontent.com/36519478/133502361-659c395a-58cf-4c6b-9234-6f7802c989b6.mp4

## Suggestion

Please add a way to visualize the data already on the store:

https://github.com/r0binxp/tableworks/blob/bc5310b1225a31f6acad210d3444475af2266297/src/store.jsx#L13-L148

I would expect to show at least an email

## Checklist

- [x] Each marker in the map has a way to identify the user it represents, for example showing the email in any way.
- [x] Clicking in another marker hides the previous user info and shows the info of the selected marker.
- [x] Clicking outside of the map or clicking in an area not belonging to a marker should hide previous information about the marker.
- [x] Previous functionality works as before.

**Comment by r0binxp** [comment]
New features added @Israel-Laguan

**Comment by Israel-Laguan** [comment]
Seems like you forgot a Pull Request but I am checking regardless.

This is a reference about the PR topic: https://www.better.dev/create-your-first-github-pull-request
